<?php

namespace API\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserPropertiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPropertiesRepository extends EntityRepository
{
}
