# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    
    api_key_user_provider:
        class: NoahGlaser\TokenAuthBundle\Security\ApiKeyUserProvider
        arguments: ["@noahglaser.tokenauth.entity.repo.token", "@api.database.entity.repo.user", 'API\DatabaseBundle\Entity\User']
    
    apikey_authenticator:
        class:     NoahGlaser\TokenAuthBundle\Security\ApiKeyAuthenticator
        arguments: ["@api_key_user_provider"]